### ISSUE TITLE
eagle branch fails to recognize existing properties

### ISSUE THREAD

**Issue by mtremmel** [pynbody/tangos#82] opened 2018-11-20 14:55 UTC
I'm currently using the eagle branch as there are some optimizations for gathering existing properties. However, this seems to make it so that TANGOS no longer recognizes when an asked-for property already exists and calculates it anyway (I did not force the calculation)

**Comment by apontzen** [comment] 2018-11-20 16:42
I think this is a duplicate of #73

**Comment by mtremmel** [comment] 2018-11-20 16:44
yes it totally is! Sorry about that!

**Closed** 2018-11-20 16:44 UTC
